import connectPgSimple from 'connect-pg-simple';
import express, { Express } from 'express';
import session from 'express-session';
import './config.js'; // do not remove this line
import {
  createQuote,
  submitAndCalculateQuote,
  updateQuoteDemolition,
  updateQuoteGrout,
  updateQuotePickup,
  updateQuoteThinSet,
} from './controllers/QuoteController.js';
import { loginUser, registerUser } from './controllers/users.js';
import { sessionMiddleware } from './sessionConfig.js';

const app: Express = express();
const { COOKIE_SECRET } = process.env;
const PostgresStore = connectPgSimple(session);

app.use(sessionMiddleware); // Setup session management middleware
app.use(express.json()); // Setup JSON body parsing middleware
app.use(express.urlencoded({ extended: false })); // Setup urlencoded (HTML Forms) body parsing middleware
app.use(
  session({
    store: new PostgresStore({ createTableIfMissing: true }),
    secret: COOKIE_SECRET, // Signs the cookie so clients can't forge it
    cookie: { maxAge: 8 * 60 * 60 * 1000 }, // 8-hour sessions
    name: 'session',
    resave: false, // Don't re-save unchanged sessions
    saveUninitialized: false, // Only create sessions when we write to req.session
  }),
);

app.use(express.json());
// Setup static resource file middleware
// This allows the client to access any file inside the `public` directory
// Only put file that you actually want to be publicly accessibly in the `public` folder
app.use(express.static('public', { extensions: ['html'] }));

// Serve the built Svelte frontend (generated by `npm run build:client`)
app.use(express.static('frontend/build'));

// -- Routes --------------------------------------------------
app.post('/api/quotes', createQuote);
app.patch('/api/quotes/:quoteId/demolition', updateQuoteDemolition);
app.patch('/api/quotes/:quoteId/grout', updateQuoteGrout);
app.patch('/api/quotes/:quoteId/pickup', updateQuotePickup);
app.patch('/api/quotes/:quoteId/thinset', updateQuoteThinSet);
app.post('/api/quotes/:quoteId/calculate', submitAndCalculateQuote);
app.post('/api/users/registerUser', registerUser);
app.post('/api/users/loginUser', loginUser);
// Register your routes below this line (prefix with `/api`)

// Returns the signed-in user (or 401). The frontend's auth store
// calls this on every page load. Replace the body once your login
// flow populates `req.session.authenticatedUser`.
app.get('/api/me', (req, res) => {
  if (!req.session.isLoggedIn || !req.session.authenticatedUser) {
    res.sendStatus(401);
    return;
  }
  const { userId, email, displayName } = req.session.authenticatedUser;
  res.json({ id: userId, email, displayName });
});

// -- SPA fallback --------------------------------------------
// Keep these LAST, after every `/api/*` route.
// Any unmatched `/api/*` request gets a JSON-safe 404.
app.use('/api', (req, res) => {
  res.sendStatus(404);
});

// Any other unmatched request falls back to the Svelte app so
// client-side routing works on refresh.
app.use((req, res) => {
  res.sendFile('index.html', { root: 'frontend/build' });
});

app.listen(process.env.PORT, () => {
  console.log(`Server listening on http://localhost:${process.env.PORT}`);
});
